/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'bharath' at '1/18/17 10:47 AM' with Gradle 2.0
 *
 * @author bharath, @date 1/18/17 10:47 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
